### ISSUE TITLE
BIP44_COIN_TYPE not changed

### ISSUE THREAD

**Issue by icodeface** [FACT0RN/FactWallet#21]
Hi, i found the BIP44_COIN_TYPE in https://github.com/FACT0RN/FactWallet/blob/master/electrum/constants.py#L102 is not changed to `42069` according to https://github.com/satoshilabs/slips/blob/master/slip-0044.md

The BIP44_COIN_TYPE creates a separate subtree for every cryptocoin, avoiding reusing addresses across cryptocoins and improving privacy issues.

**Comment by ReverseControl** [comment]
Thank you. We will address this.

**Comment by silkyjohnson1** [comment]
opened pull req
