### ISSUE TITLE
this wallet can't connect node

### ISSUE THREAD

**Issue by differs** [FACT0RN/FactWallet#23]

**Comment by ReverseControl** [comment]
More nodes are coming online this week. There will be an update to this open issue once more official nodes have been added.

**Comment by ReverseControl** [comment]
The FactWallet now has three servers:

[http://electrumx.fact0rn.io:50002](https://t.co/WiVg9dZXC1)
[http://electrumx2.fact0rn.io:50002](https://t.co/HHfp2aJSJW)
[http://electrumx3.fact0rn.io:50002](https://t.co/jAG1Yx15dz)

The next release will include these by default. In the meantime, you can grab them from here if you wish to connect to a different server.
